server:
  port: 8761
         
#Spring config
spring:
  application:
    name: EUREKA-SERVER        
        
#Eureka client
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false